/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 crystal_planet.gltf --transform 
Files: crystal_planet.gltf [58.2MB] > crystal_planet-transformed.glb [5.69MB] (90%)
Author: ahingel (https://sketchfab.com/ahingel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crystal-planet-7a95246b6eda448d98a236b91474bcbb
Title: Crystal Planet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/crystal_planet-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} position={[-0.793, 0.358, 0]} rotation={[-Math.PI / 2, 0, -0.847]} scale={0.069} />
      <mesh geometry={nodes.main_planet_main_planet_0.geometry} material={materials.main_planet} rotation={[-Math.PI / 2, 0, -0.847]} scale={1.986} />
      <mesh geometry={nodes.main_crystal_main_crystal_0.geometry} material={materials.main_crystal} position={[0.07, 0.379, 0.036]} rotation={[-Math.PI / 2, 0, -0.847]} scale={0.18} />
      <mesh geometry={nodes.saturn_saturn_0.geometry} material={materials.saturn} position={[0.428, 1.855, -4.002]} rotation={[-Math.PI / 2, 0, -0.347]} scale={0.687} />
      <mesh geometry={nodes.saturn_ring_saturn_0.geometry} material={materials.ring_saturn} position={[0.428, 1.855, -4.002]} rotation={[-Math.PI / 2, 0, -0.347]} scale={0.687} />
      <mesh geometry={nodes.Sphere002_small_crystal_planet_0.geometry} material={materials.small_crystal_planet} position={[0, 2.589, 2.803]} rotation={[-Math.PI / 2, 0, 0]} scale={0.687} />
      <mesh geometry={nodes.tree_planet_tree_planet_0.geometry} material={materials.tree_planet} position={[-4.514, 0.681, -2.369]} rotation={[-Math.PI / 2, 0, 0]} scale={1.986} />
      <mesh geometry={nodes.small_rocks_small_rocks_0.geometry} material={materials.small_rocks} rotation={[-Math.PI / 2, 0, 0]} scale={1.986} />
      <mesh geometry={nodes.tree_bark_tree_bark_0.geometry} material={materials.tree_bark} position={[-4.571, 1.546, -2.476]} rotation={[-Math.PI / 2, 0, 1.152]} scale={0.21} />
      <mesh geometry={nodes.leaves_twig_0.geometry} material={materials.twig} position={[-4.863, 2.045, -5.428]} rotation={[-1.514, 0.405, 2.371]} scale={0.347} />
      <mesh geometry={nodes.leaves_leaves_0.geometry} material={materials.leaves} position={[-4.863, 2.045, -5.428]} rotation={[-1.514, 0.405, 2.371]} scale={0.347} />
    </group>
  )
}

useGLTF.preload('/crystal_planet-transformed.glb')
