/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 esferas_del_dragon.gltf --transform 
Files: esferas_del_dragon.gltf [119.41KB] > esferas_del_dragon-transformed.glb [70.41KB] (41%)
Author: Andres Zuluaga (https://sketchfab.com/afzmtm)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/esferas-del-dragon-2dccd89103da4e1fbe03a2b136f36302
Title: Esferas Del Dragon
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/esferas_del_dragon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_3.geometry} material={materials.pasted__blinn1SG} position={[-8.139, -0.006, 9.139]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.pasted__lambert2SG} position={[-8.139, -0.006, 9.139]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/esferas_del_dragon-transformed.glb')
