/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 mastered_ultra_instinct_-_goku.gltf --transform 
Files: mastered_ultra_instinct_-_goku.gltf [3.51MB] > mastered_ultra_instinct_-_goku-transformed.glb [2.57MB] (27%)
Author: Alex Belalis Designs (https://sketchfab.com/alexbelalisdesigns)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mastered-ultra-instinct-goku-bba122ffa0d949cea97a67d21db87625
Title: Mastered Ultra Instinct - Goku
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/mastered_ultra_instinct_-_goku-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.001}>
          <group name="Sphere002" position={[-15.255, 37.378, -22.856]} rotation={[1.046, -0.034, 1.322]} scale={[-0.728, -0.599, -1.197]}>
            <mesh name="Sphere002__0" geometry={nodes.Sphere002__0.geometry} material={materials.Cube__0} />
          </group>
        </group>
        <mesh name="Cube__0" geometry={nodes.Cube__0.geometry} material={materials.Cube__0} position={[0.243, 0.126, 0.209]} rotation={[-Math.PI / 2, 0, 0]} scale={0.082} />
        <mesh name="Hair002_Energy_0" geometry={nodes.Hair002_Energy_0.geometry} material={materials.Energy} position={[0.003, -0.002, 0.015]} scale={0.064} />
        <mesh name="Hair001_Energy_001_0" geometry={nodes.Hair001_Energy_001_0.geometry} material={materials.Energy_001} position={[0.003, -0.002, 0.015]} scale={0.064} />
        <mesh name="Head_Material001_0" geometry={nodes.Head_Material001_0.geometry} material={materials['Material.001']} position={[-0.002, 0.452, -0.003]} rotation={[-2.967, -1.484, Math.PI]} scale={0.064} />
        <mesh name="Clothes_Material004_0" geometry={nodes.Clothes_Material004_0.geometry} material={materials['Material.004']} position={[0, 0.211, 0.023]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.157, 0.09, 0.163]} />
        <mesh name="Ears_Material003_0" geometry={nodes.Ears_Material003_0.geometry} material={materials['Material.003']} position={[-0.06, 0.526, -0.004]} rotation={[-1.574, 0.297, -0.59]} scale={[0.005, 0.024, 0.031]} />
        <mesh name="Hair_GokuHair_0" geometry={nodes.Hair_GokuHair_0.geometry} material={materials.GokuHair} position={[2.72, 0.013, 0]} scale={0.064} />
        <mesh name="Arms_Material002_0" geometry={nodes.Arms_Material002_0.geometry} material={materials['Material.002']} position={[-0.068, -1.102, 0]} scale={0.025} />
        <mesh name="Plane009_Material005_0" geometry={nodes.Plane009_Material005_0.geometry} material={materials['Material.005']} position={[0.138, 0.17, 0.012]} rotation={[-1.341, -0.802, 1.814]} scale={0.041} />
        <mesh name="Shoes_tex4png_0" geometry={nodes.Shoes_tex4png_0.geometry} material={materials['tex4.png']} position={[-0.12, -0.789, -0.145]} rotation={[0.212, -0.251, 0.081]} scale={[-0.022, 0.02, 0.02]} />
        <mesh name="Sphere_Material009_0" geometry={nodes.Sphere_Material009_0.geometry} material={materials['Material.009']} position={[0.243, 0.128, 0.209]} rotation={[-Math.PI / 2, 0, 0]} scale={0.052} />
      </group>
    </group>
  )
}

useGLTF.preload('/mastered_ultra_instinct_-_goku-transformed.glb')
