/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 shenron_dragon_ball.gltf --transform 
Files: shenron_dragon_ball.gltf [2.09MB] > shenron_dragon_ball-transformed.glb [461.95KB] (78%)
Author: Anthony Yanez (https://sketchfab.com/paulyanez)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shenron-dragon-ball-96e8ad1e206941ce859c5733bec75d30
Title: Shenron (Dragon Ball)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shenron_dragon_ball-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Shenron_Green_0.geometry} material={materials.Green} position={[-5.587, 5.538, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Shenron_Yellow_0.geometry} material={materials.Yellow} position={[-5.587, 5.538, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Shenron_09_-_Default_0'].geometry} material={materials['09_-_Default']} position={[-5.587, 5.538, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['Shenron_08_-_Default_0'].geometry} material={materials['08_-_Default']} position={[-5.587, 5.538, 0]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['One_Star_02_-_Default_0'].geometry} material={materials['02_-_Default']} position={[2.812, 0, -0.392]} rotation={[-Math.PI / 3, 0, 0]} scale={0.048} />
      <mesh geometry={nodes['One_Star_03_-_Default_0'].geometry} material={materials['03_-_Default']} position={[2.812, 0, -0.392]} rotation={[-Math.PI / 3, 0, 0]} scale={0.048} />
    </group>
  )
}

useGLTF.preload('/shenron_dragon_ball-transformed.glb')
